### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by presto8** [drynish/python-chargepoint#1]
Hello, I am interesting in packaging this module for nixos. But in order to do that, the project needs a license. Would it be possible to add a license? Thank you!

**Comment by drynish** [comment]
Oh I stopped supporting it, I change from Chargepoint to TechnoVE

**Comment by presto8** [comment]
Are you looking for a new maintainer? I could volunteer to take it over if so :) Thanks for adding the license in the meantime.
